name: Build and Deploy (Eleventy → GitHub Pages)

on:
  push:
    branches: [main]
    paths:
      - "index.njk"
      - "_includes/**"
      - "_data/**"
      - "eleventy.config.js"
      - "src/**"
      - "projects/**"
      - "robots.njk"
      - "sitemap.njk"
      - "404.njk"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install
        run: npm ci

      - name: Build (Eleventy)
        env:
          # Project-site prefix = /<repo-name>
          PATH_PREFIX: "/${{ github.event.repository.name }}"
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
